ALTER TABLE "Settings"
ADD COLUMN IF NOT EXISTS "footerBrandTitle" TEXT DEFAULT 'Ruby Beauty',
ADD COLUMN IF NOT EXISTS "footerBrandTitleAr" TEXT DEFAULT 'Ruby Beauty',
ADD COLUMN IF NOT EXISTS "footerBrandDescription" TEXT DEFAULT 'Premium botanical skincare designed to reveal your natural radiance. Cruelty-free, vegan, and sustainable.',
ADD COLUMN IF NOT EXISTS "footerBrandDescriptionAr" TEXT DEFAULT 'منتجات عناية بالبشرة نباتية فاخرة مصممة لإظهار إشراقتك الطبيعية. خالية من القسوة، نباتية ومستدامة.',
ADD COLUMN IF NOT EXISTS "footerCopyright" TEXT DEFAULT '© 2026 Ruby Beauty. All rights reserved.',
ADD COLUMN IF NOT EXISTS "footerCopyrightAr" TEXT DEFAULT '© 2026 روبي بيوتي. جميع الحقوق محفوظة.',
ADD COLUMN IF NOT EXISTS "footerInstagramUrl" TEXT DEFAULT 'https://www.instagram.com/ruby.beauty.sy',
ADD COLUMN IF NOT EXISTS "footerFacebookUrl" TEXT DEFAULT 'https://www.facebook.com/share/1HzXdo7sLG/?mibextid=wwXIfr',
ADD COLUMN IF NOT EXISTS "footerWhatsappUrl" TEXT DEFAULT 'https://wa.me/963933254796',
ADD COLUMN IF NOT EXISTS "footerShopTitle" TEXT DEFAULT 'Shop',
ADD COLUMN IF NOT EXISTS "footerShopTitleAr" TEXT DEFAULT 'المتجر',
ADD COLUMN IF NOT EXISTS "footerSupportTitle" TEXT DEFAULT 'Support',
ADD COLUMN IF NOT EXISTS "footerSupportTitleAr" TEXT DEFAULT 'الدعم',
ADD COLUMN IF NOT EXISTS "footerCompanyTitle" TEXT DEFAULT 'Company',
ADD COLUMN IF NOT EXISTS "footerCompanyTitleAr" TEXT DEFAULT 'الشركة',
ADD COLUMN IF NOT EXISTS "footerSupportLink1Label" TEXT DEFAULT 'Help Center',
ADD COLUMN IF NOT EXISTS "footerSupportLink1LabelAr" TEXT DEFAULT 'مركز المساعدة',
ADD COLUMN IF NOT EXISTS "footerSupportLink1Url" TEXT DEFAULT 'https://wa.me/963933254796',
ADD COLUMN IF NOT EXISTS "footerSupportLink2Label" TEXT DEFAULT 'Shipping & Returns',
ADD COLUMN IF NOT EXISTS "footerSupportLink2LabelAr" TEXT DEFAULT 'الشحن والإرجاع',
ADD COLUMN IF NOT EXISTS "footerSupportLink2Url" TEXT DEFAULT '/shipping-returns',
ADD COLUMN IF NOT EXISTS "footerSupportLink3Label" TEXT DEFAULT 'Contact Us',
ADD COLUMN IF NOT EXISTS "footerSupportLink3LabelAr" TEXT DEFAULT 'اتصل بنا',
ADD COLUMN IF NOT EXISTS "footerSupportLink3Url" TEXT DEFAULT 'https://wa.me/963933254796',
ADD COLUMN IF NOT EXISTS "footerCompanyLink1Label" TEXT DEFAULT 'About Us',
ADD COLUMN IF NOT EXISTS "footerCompanyLink1LabelAr" TEXT DEFAULT 'من نحن',
ADD COLUMN IF NOT EXISTS "footerCompanyLink1Url" TEXT DEFAULT '/about-us',
ADD COLUMN IF NOT EXISTS "footerCompanyLink2Label" TEXT,
ADD COLUMN IF NOT EXISTS "footerCompanyLink2LabelAr" TEXT,
ADD COLUMN IF NOT EXISTS "footerCompanyLink2Url" TEXT,
ADD COLUMN IF NOT EXISTS "footerCompanyLink3Label" TEXT,
ADD COLUMN IF NOT EXISTS "footerCompanyLink3LabelAr" TEXT,
ADD COLUMN IF NOT EXISTS "footerCompanyLink3Url" TEXT,
ADD COLUMN IF NOT EXISTS "footerCategory1Id" TEXT,
ADD COLUMN IF NOT EXISTS "footerCategory2Id" TEXT,
ADD COLUMN IF NOT EXISTS "footerCategory3Id" TEXT,
ADD COLUMN IF NOT EXISTS "footerCategory4Id" TEXT;
